/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Moon
 */
public class GUI_InformacionUsuario extends javax.swing.JPanel {

    /**
     * Creates new form GUI_InformacionUsuario
     */
    public GUI_InformacionUsuario() {
        initComponents();
        cargarComboBox();
    }
    
    public void cargarComboBox()
    {
        this.jcb_Popularidad.removeAllItems();
        
        for(int contador=0; contador<11; contador++)
        {
            this.jcb_Popularidad.addItem(""+contador);
        }
       this.jcb_Popularidad.setSelectedIndex(6);
    }
    
    public String[] devolverDatos()
    {
        String arreglo[];
        arreglo=new String[3];
        
        arreglo[0]=this.jt_codigo.getText();
        arreglo[1]=this.jt_Nombre.getText();
        arreglo[2]=""+this.jcb_Popularidad.getSelectedIndex();
        
        return arreglo;
    }
    
    public void mostrarInformacion(String arreglo[])
    {
       this.jt_Nombre.setText(arreglo[0]);
       this.jcb_Popularidad.setSelectedIndex(Integer.parseInt(arreglo[1]));
    }
    
    public String devolverCodigo()
    {
        return this.jt_codigo.getText();
    }
    
    public void limpiar()
    {
        this.jt_Nombre.setText("");
        this.jt_codigo.setText("");
        this.jcb_Popularidad.setSelectedIndex(6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_codigo = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jl_Popularidad = new javax.swing.JLabel();
        jt_codigo = new javax.swing.JTextField();
        jt_Nombre = new javax.swing.JTextField();
        jcb_Popularidad = new javax.swing.JComboBox<>();

        jl_codigo.setText("Codigo");

        jl_Nombre.setText("Nombre");

        jl_Popularidad.setText("Popularidad");

        jcb_Popularidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_Popularidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_PopularidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_codigo)
                    .addComponent(jl_Nombre)
                    .addComponent(jl_Popularidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jt_codigo)
                    .addComponent(jt_Nombre)
                    .addComponent(jcb_Popularidad, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_codigo)
                    .addComponent(jt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre)
                    .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_Popularidad)
                    .addComponent(jcb_Popularidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_PopularidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_PopularidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_PopularidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jcb_Popularidad;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_Popularidad;
    private javax.swing.JLabel jl_codigo;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextField jt_codigo;
    // End of variables declaration//GEN-END:variables
}
